name: Check and Update pubspec.yaml on Release Branch

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  check-and-update-pubspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.0'

    - name: Check and Update Dependencies in pubspec.yaml
      run: |
        # Replace specific dependency refs with their respective branches
        sed -i 's/ref: [a-zA-Z0-9_-]* # coindcx_core/ref: develop # coindcx_core/g' pubspec.yaml
        sed -i 's/ref: [a-zA-Z0-9_-]* # coindcx_ui_components/ref: release # coindcx_ui_components/g' pubspec.yaml
        sed -i 's/ref: [a-zA-Z0-9_-]* # webview_dcx/ref: stable # webview_dcx/g' pubspec.yaml
        sed -i 's/ref: [a-zA-Z0-9_-]* # ui_kit_dcx/ref: defi_release_new # ui_kit_dcx/g' pubspec.yaml
        sed -i 's/ref: [a-zA-Z0-9_-]* # okto_mobile_sdk/ref: DS-377 # okto_mobile_sdk/g' pubspec.yaml
        # Add more sed commands for other dependencies as needed

    - name: Check for Changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to commit."
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"
          git add pubspec.yaml
          git commit -m "Update dependencies to reference their specific branches"
          git push
        else
          echo "No changes detected. Skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
